/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:4f992ced-9436-4a0e-8e4d-ec9e58ec5666",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_1tI3wrwOz",
    "aws_user_pools_web_client_id": "4qtobc6rugb5047nh0otmt1bdc",
    "oauth": {}
};


export default awsmobile;
