/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:26fb32b5-abf1-4fc6-a469-9d2d44da745d",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_H3xN5wGNo",
    "aws_user_pools_web_client_id": "3f41p2iobgnqte684ssnnjsis2",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://bfjh2nheiffodl2kbwananwvlu.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
